# Generated by Django 2.0.3 on 2018-12-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181222_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('MONEY', 'Money'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card')], default='CREDIT_CARD', max_length=50),
        ),
    ]
